apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqlschemas.mysql.sample.javaoperatorsdk
spec:
  group: mysql.sample.javaoperatorsdk
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
             spec:
               type: object
               required:
                 - encoding
               properties:
                 encoding:
                   type: string
  scope: Namespaced
  names:
    plural: mysqlschemas
    singular: mysqlschema
    kind: MySQLSchema