name: Tomcat integration test
on:
   push:
      branches:
      - "*"
jobs: 
    helm_chart_validation:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Set up Helm
          uses: azure/setup-helm@v1
          with:
            version: v3.4.0
  
        - uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - name: Create kind cluster
          uses: helm/kind-action@v1.2.0
  
        - name: Check pods
          run: kubectl get pods -A
        - uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - name: Set up Java and Maven
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
        - uses: actions/cache@v2
          with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        - name: Run unit tests
          run: mvn -B test --file tomcat/pom.xml